#!/bin/bash

echo "oh-my-zsh"
curl -L http://install.ohmyz.sh | sh >> CroutonSetup.log 2>> CroutonSetup.errors

echo "talapus zsh theme copied to ~/.oh-my-zsh/themes"
cp -v talapus.zsh-theme ~/.oh-my-zsh/themes >> CroutonSetup.log 2>> CroutonSetup.errors

echo "Installing Janus VIM extensions https://github.com/carlhuda/janus"
curl -Lo- https://bit.ly/janus-bootstrap | bash >> CroutonSetup.log 2>> CroutonSetup.errors  

mkdir ~/Repositories
mkdir ~/.bin
mkdir ~/.Tasks
