#!/bin/bash

echo "Crouton setup script..."
sudo apt-get update  

echo "Freshening packages"
sudo apt-get upgrade -y 

# Remove xscreensaver
echo "Removing xscreensaver"
sudo apt-get purge xscreensaver -y  

# System tools
echo "Utilities"
sudo apt-get install locate -y 
sudo apt-get install mtr -y 
sudo apt-get install curl -y 

# Devtools
echo "Tools"
sudo apt-get install vim -y 
sudo apt-get install zsh -y 
sudo apt-get install ruby -y
sudo apt-get install rake -y 
sudo apt-get install python -y 
sudo apt-get install python-pip -y 

# toys
echo "Top Secret Mission Critical Software"
sudo apt-get install fortune -y 
sudo apt-get install cowsay -y 
sudo apt-get install figlet -y

# first launch of zsh. Create the default file. 
zsh

echo "Cleanup"
sudo apt-get autoremove 

mkdir ~/Repositories
mkdir ~/.bin
mkdir ~/.Tasks
